/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 05-Apr-2016 11:31:43 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `comment` CASCADE
;

DROP TABLE IF EXISTS `slide` CASCADE
;

DROP TABLE IF EXISTS `subject` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `comment`
(
	`slideid` INT NOT NULL,
	`userid` INT NOT NULL,
	`content` TEXT 	 NULL,
	`time` DATETIME 	 NULL,
	`commentid` INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT `PK_comment` PRIMARY KEY (`commentid` ASC)
)

;

CREATE TABLE `slide`
(
	`slideid` INT NOT NULL AUTO_INCREMENT,
	`userid` INT 	 NULL,
	`url` TEXT NOT NULL,
	`subjectid` INT 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`slideid` ASC)
)
COMMENT='Info about slide'

;

CREATE TABLE `subject`
(
	`subjectid` INT NOT NULL AUTO_INCREMENT,
	`name` CHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`subjectid` ASC)
)

;

CREATE TABLE `user`
(
	`userid` INT NOT NULL AUTO_INCREMENT,
	`username` CHAR(20) 	 NULL,
	`password` CHAR(20) 	 NULL,
	`userright` CHAR(10) 	 NULL DEFAULT user,
	CONSTRAINT `PK_user` PRIMARY KEY (`userid` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `comment` 
 ADD INDEX `IXFK_comment_slide` (`slideid` ASC)
;

ALTER TABLE `comment` 
 ADD INDEX `IXFK_comment_user` (`userid` ASC)
;

ALTER TABLE `slide` 
 ADD INDEX `IXFK_slide_subject` (`subjectid` ASC)
;

ALTER TABLE `slide` 
 ADD INDEX `IXFK_slide_user` (`slideid` ASC)
;

ALTER TABLE `slide` 
 ADD INDEX `IXFK_slide_user_02` (`userid` ASC)
;

ALTER TABLE `slide` 
 ADD INDEX `IXFK_slide_user_03` (`userid` ASC)
;

ALTER TABLE `user` 
 ADD CONSTRAINT `ct1` UNIQUE (`username` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_slide`
	FOREIGN KEY (`slideid`) REFERENCES `slide` (`slideid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `comment` 
 ADD CONSTRAINT `FK_comment_user`
	FOREIGN KEY (`userid`) REFERENCES `user` (`userid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `slide` 
 ADD CONSTRAINT `FK_slide_subject`
	FOREIGN KEY (`subjectid`) REFERENCES `subject` (`subjectid`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `slide` 
 ADD CONSTRAINT `FK_slide_user`
	FOREIGN KEY (`userid`) REFERENCES `user` (`userid`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
